const en = {
  translation: {
    // Common
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.noData": "No data available.",

    // Auth
    "login.title": "Sign In",
    "login.subtitle": "Access your IT management system",
    "login.email": "Email",
    "login.password": "Password",
    "login.showPassword": "Show password",
    "login.hidePassword": "Hide password",
    "login.submit": "Sign In",
    "login.loading": "Signing in...",
    "login.required": "All fields are required.",
    "login.error": "Invalid credentials",
    "login.forgotPassword": "Forgot your password?",
    "login.heroTitle": "Manage your IT infrastructure",
    "login.heroSubtitle": "One platform for devices, maintenance, licenses, and support.",

    // Forgot password
    "forgot.title": "Reset Password",
    "forgot.subtitle": "Enter your email address and we'll send you a reset code.",
    "forgot.sendCode": "Send Reset Code",
    "forgot.sending": "Sending...",
    "forgot.enterCodeTitle": "Enter Reset Code",
    "forgot.enterCodeDesc": "We sent a 6-character code to",
    "forgot.code": "Reset Code",
    "forgot.newPassword": "New Password",
    "forgot.newPasswordPlaceholder": "Min. 8 characters",
    "forgot.resetPassword": "Reset Password",
    "forgot.resetting": "Resetting...",
    "forgot.successTitle": "Password Updated!",
    "forgot.successDesc": "Your password has been changed successfully. You can now sign in.",
    "forgot.backToLogin": "Back to Sign In",
    "forgot.changeEmail": "Use different email",
    "forgot.errorSend": "Failed to send code. Please try again.",
    "forgot.errorReset": "Failed to reset password. Check the code and try again.",
    "forgot.passwordTooShort": "Password must be at least 8 characters.",

    // Setup (first-run)
    "setup.title": "Create Your First Company",
    "setup.subtitle": "Welcome! Set up your organization to start using the system.",
    "setup.companyName": "Company Name",
    "setup.companyNamePlaceholder": "Acme Technologies Inc.",
    "setup.email": "Email",
    "setup.phone": "Phone",
    "setup.address": "Address",
    "setup.addressPlaceholder": "123 Main St, City",
    "setup.ruc": "Tax ID / RUC",
    "setup.createCompany": "Create Company",
    "setup.creating": "Creating...",
    "setup.doneTitle": "Company Created!",
    "setup.doneDesc": "Your company is ready:",
    "setup.goToDashboard": "Go to Dashboard",
    "setup.errorCreate": "Failed to create company. Please try again.",

    // Profile page
    "profile.loadError": "Could not load profile.",
    "profile.edit": "Edit Profile",
    "profile.settings": "Settings",
    "profile.personal": "Personal Information",
    "profile.contact": "Contact Information",
    "profile.professional": "Professional Information",
    "profile.system": "System Information",
    "profile.companies": "Assigned Companies",
    "profile.firstName": "First Name",
    "profile.lastName": "Last Name",
    "profile.userCode": "User Code",
    "profile.userId": "User ID",
    "profile.primaryEmail": "Primary Email",
    "profile.contactEmail": "Contact Email",
    "profile.phone": "Phone",
    "profile.username": "Username",
    "profile.department": "Department",
    "profile.position": "Position",
    "profile.role": "System Role",
    "profile.createdAt": "Created",
    "profile.updatedAt": "Last Updated",
    "profile.personId": "Person ID",
    "profile.accountActive": "Account Active",
    "profile.active": "Active",
    "profile.inactive": "Inactive",
    "profile.yes": "Yes",
    "profile.no": "No",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.devices": "Devices",
    "nav.maintenance": "Maintenance",
    "nav.network": "Network",
    "nav.users": "Users",
    "nav.persons": "Persons",
    "nav.tickets": "Tickets",
    "nav.expenses": "Expenses",
    "nav.licenses": "Licenses",
    "nav.documents": "Documents",
    "nav.reports": "Reports",
    "nav.inventory": "Inventory",
    "nav.settings": "Settings",
    "nav.logout": "Sign Out",
    "nav.profile": "Profile",
    "nav.noAccess": "You don't have access to any route",
    "nav.openMenu": "Open main menu",
    "nav.closeMenu": "Close main menu",
    "nav.closeSidebar": "Close sidebar",

    // Common actions
    "action.create": "Create",
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.export": "Export",
    "action.import": "Import",
    "action.search": "Search",
    "action.filter": "Filter",
    "action.view": "View",
    "action.download": "Download",
    "action.upload": "Upload",
    "action.report": "Report",
    "action.confirm": "Confirm",
    "action.back": "Back",
    "action.next": "Next",
    "action.submit": "Submit",
    "action.update": "Update",
    "action.refresh": "Refresh",
    "action.downloadTemplate": "Download Template",
    "action.importCSV": "Import CSV",
    "action.importing": "Importing...",

    // Common labels
    "common.loading": "Loading...",
    "common.saving": "Saving...",
    "common.deleting": "Deleting...",
    "common.noData": "No data available.",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.date": "Date",
    "common.name": "Name",
    "common.description": "Description",
    "common.type": "Type",
    "common.category": "Category",
    "common.company": "Company",
    "common.notes": "Notes",
    "common.selected": "selected",
    "common.total": "Total",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.enabled": "Enabled",
    "common.disabled": "Disabled",
    "common.yes": "Yes",
    "common.no": "No",
    "common.all": "All",
    "common.none": "None",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.confirmDelete": "Are you sure you want to delete this item?",
    "common.cannotUndo": "This action cannot be undone.",
    "common.error": "An error occurred",
    "common.success": "Operation successful",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome",
    "dashboard.totalDevices": "Total Devices",
    "dashboard.openTickets": "Open Tickets",
    "dashboard.expiringLicenses": "Expiring Licenses",
    "dashboard.pendingMaintenance": "Pending Maintenance",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.systemOverview": "System Overview",
    "dashboard.quickStats": "Quick Stats",

    // Devices
    "devices.title": "Devices",
    "devices.all": "All Devices",
    "devices.create": "New Device",
    "devices.edit": "Edit Device",
    "devices.serialNumber": "Serial Number",
    "devices.brand": "Brand",
    "devices.model": "Model",
    "devices.location": "Location",
    "devices.assignedTo": "Assigned To",
    "devices.purchaseDate": "Purchase Date",
    "devices.warrantyExpiry": "Warranty Expiry",
    "devices.ipAddress": "IP Address",
    "devices.macAddress": "MAC Address",
    "devices.operatingSystem": "Operating System",
    "devices.processor": "Processor",
    "devices.ram": "RAM",
    "devices.storage": "Storage",
    "devices.totalDevices": "Total Devices",
    "devices.assigned": "Assigned",
    "devices.unassigned": "Unassigned",
    "devices.inWarranty": "In Warranty",
    "devices.deleteConfirm": "Delete device?",

    // Maintenance
    "maintenance.title": "Maintenance",
    "maintenance.all": "All Maintenance",
    "maintenance.create": "New Maintenance",
    "maintenance.edit": "Edit Maintenance",
    "maintenance.type": "Maintenance Type",
    "maintenance.scheduledDate": "Scheduled Date",
    "maintenance.completedDate": "Completed Date",
    "maintenance.technician": "Technician",
    "maintenance.cost": "Cost",
    "maintenance.priority": "Priority",
    "maintenance.pending": "Pending",
    "maintenance.inProgress": "In Progress",
    "maintenance.completed": "Completed",
    "maintenance.cancelled": "Cancelled",
    "maintenance.preventive": "Preventive",
    "maintenance.corrective": "Corrective",
    "maintenance.totalMaintenance": "Total Maintenance",
    "maintenance.pendingCount": "Pending",
    "maintenance.completedCount": "Completed",
    "maintenance.deleteConfirm": "Delete maintenance record?",

    // Network
    "network.title": "Network",
    "network.all": "All Network",
    "network.create": "New Network Device",
    "network.edit": "Edit Network Device",
    "network.ipAddress": "IP Address",
    "network.macAddress": "MAC Address",
    "network.subnet": "Subnet",
    "network.gateway": "Gateway",
    "network.dns": "DNS",
    "network.vlan": "VLAN",
    "network.port": "Port",
    "network.bandwidth": "Bandwidth",
    "network.totalDevices": "Total Network Devices",
    "network.online": "Online",
    "network.offline": "Offline",
    "network.deleteConfirm": "Delete network device?",

    // Users
    "users.title": "Users",
    "users.all": "All Users",
    "users.create": "New User",
    "users.edit": "Edit User",
    "users.email": "Email",
    "users.role": "Role",
    "users.password": "Password",
    "users.confirmPassword": "Confirm Password",
    "users.lastLogin": "Last Login",
    "users.totalUsers": "Total Users",
    "users.admins": "Admins",
    "users.deleteConfirm": "Delete user?",
    "users.superAdmin": "Super Admin",
    "users.admin": "Admin",
    "users.moderator": "Moderator",
    "users.user": "User",

    // Persons
    "persons.title": "Persons",
    "persons.all": "All Persons",
    "persons.create": "New Person",
    "persons.edit": "Edit Person",
    "persons.firstName": "First Name",
    "persons.lastName": "Last Name",
    "persons.phone": "Phone",
    "persons.department": "Department",
    "persons.position": "Position",
    "persons.totalPersons": "Total Persons",
    "persons.withDevice": "With Device",
    "persons.deleteConfirm": "Delete person?",

    // Tickets
    "tickets.title": "Tickets",
    "tickets.all": "All Tickets",
    "tickets.create": "New Ticket",
    "tickets.edit": "Edit Ticket",
    "tickets.subject": "Subject",
    "tickets.requester": "Requester",
    "tickets.assignedTo": "Assigned To",
    "tickets.priority": "Priority",
    "tickets.status": "Status",
    "tickets.open": "Open",
    "tickets.inProgress": "In Progress",
    "tickets.resolved": "Resolved",
    "tickets.closed": "Closed",
    "tickets.low": "Low",
    "tickets.medium": "Medium",
    "tickets.high": "High",
    "tickets.critical": "Critical",
    "tickets.totalTickets": "Total Tickets",
    "tickets.openCount": "Open",
    "tickets.resolvedCount": "Resolved",
    "tickets.deleteConfirm": "Delete ticket?",

    // Expenses
    "expenses.title": "Expenses",
    "expenses.all": "All Expenses",
    "expenses.create": "New Expense",
    "expenses.edit": "Edit Expense",
    "expenses.amount": "Amount",
    "expenses.vendor": "Vendor",
    "expenses.invoiceNumber": "Invoice Number",
    "expenses.paymentDate": "Payment Date",
    "expenses.software": "Software",
    "expenses.annual": "Annual",
    "expenses.totalExpenses": "Total Expenses",
    "expenses.annualTotal": "Annual Total",
    "expenses.deleteConfirm": "Delete expense?",

    // Licenses
    "licenses.title": "Software Licenses",
    "licenses.all": "All Licenses",
    "licenses.create": "New License",
    "licenses.edit": "Edit License",
    "licenses.softwareName": "Software",
    "licenses.licenseKey": "License Key",
    "licenses.provider": "Provider",
    "licenses.activationDate": "Activation Date",
    "licenses.expirationDate": "Expiration Date",
    "licenses.noExpiration": "No expiration",
    "licenses.active": "Active",
    "licenses.expiringSoon": "Expiring Soon",
    "licenses.expired": "Expired",
    "licenses.totalLicenses": "Total Licenses",
    "licenses.expiringSoonCount": "Expiring (30 days)",
    "licenses.expiredCount": "Expired",
    "licenses.deleteConfirm": "Delete license?",

    // Documents
    "documents.title": "Documents",
    "documents.all": "All Documents",
    "documents.create": "Upload Document",
    "documents.edit": "Edit Document",
    "documents.fileUrl": "File URL",
    "documents.fileType": "File Type",
    "documents.equipment": "Associated Equipment",
    "documents.noCategory": "No Category",
    "documents.totalDocuments": "Total Documents",
    "documents.categories": "Categories",
    "documents.withEquipment": "With Equipment",
    "documents.deleteConfirm": "Delete document?",

    // Reports
    "reports.title": "IT Reports",
    "reports.all": "All Reports",
    "reports.generate": "Generate Report",
    "reports.dateRange": "Date Range",
    "reports.from": "From",
    "reports.to": "To",

    // Inventory
    "inventory.title": "Inventory",
    "inventory.all": "All Inventory",
    "inventory.create": "New Item",
    "inventory.edit": "Edit Item",
    "inventory.quantity": "Quantity",
    "inventory.unitPrice": "Unit Price",
    "inventory.totalValue": "Total Value",
    "inventory.deleteConfirm": "Delete inventory item?",

    // Settings
    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.darkMode": "Dark Mode",
    "settings.lightMode": "Light Mode",
    "settings.profile": "Profile",
    "settings.company": "Company",

    // Errors
    "error.notFound": "Page not found",
    "error.unauthorized": "Unauthorized",
    "error.serverError": "Server error",
    "error.networkError": "Network error",
    "error.loadData": "Error loading data",
    "error.saveData": "Error saving data",
    "error.deleteData": "Error deleting item",
    "error.selectCompany": "Please select a company first",

    // Language
    "lang.en": "English",
    "lang.es": "Spanish",
    "lang.switch": "Switch language",
  },
};

export default en;
