const es = {
  translation: {
    // Común
    "common.search": "Buscar",
    "common.loading": "Cargando...",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.create": "Crear",
    "common.noData": "No hay datos disponibles.",

    // Auth
    "login.title": "Iniciar Sesión",
    "login.subtitle": "Accede a tu sistema de gestión IT",
    "login.email": "Correo Electrónico",
    "login.password": "Contraseña",
    "login.showPassword": "Mostrar contraseña",
    "login.hidePassword": "Ocultar contraseña",
    "login.submit": "Iniciar Sesión",
    "login.loading": "Iniciando sesión...",
    "login.required": "Todos los campos son obligatorios.",
    "login.error": "Credenciales inválidas",
    "login.errorCredentials": "Correo o contraseña incorrectos. Por favor intenta de nuevo.",
    "login.errorServer": "No se pudo conectar al servidor. Verifica tu conexión o intenta más tarde.",
    "login.errorUnknown": "Ocurrió un error inesperado. Por favor intenta de nuevo.",
    "login.forgotPassword": "¿Olvidaste tu contraseña?",
    "login.heroTitle": "Gestiona tu infraestructura de TI",
    "login.heroSubtitle": "Una plataforma para dispositivos, mantenimiento, licencias y soporte.",

    // Recuperar contraseña
    "forgot.title": "Recuperar Contraseña",
    "forgot.subtitle": "Ingresa tu correo y te enviaremos un código de recuperación.",
    "forgot.sendCode": "Enviar Código",
    "forgot.sending": "Enviando...",
    "forgot.enterCodeTitle": "Ingresa el Código",
    "forgot.enterCodeDesc": "Enviamos un código de 6 caracteres a",
    "forgot.code": "Código de Recuperación",
    "forgot.newPassword": "Nueva Contraseña",
    "forgot.newPasswordPlaceholder": "Mín. 8 caracteres",
    "forgot.resetPassword": "Cambiar Contraseña",
    "forgot.resetting": "Cambiando...",
    "forgot.successTitle": "¡Contraseña Actualizada!",
    "forgot.successDesc": "Tu contraseña fue cambiada exitosamente. Ya puedes iniciar sesión.",
    "forgot.backToLogin": "Volver al Inicio de Sesión",
    "forgot.changeEmail": "Usar otro correo",
    "forgot.errorSend": "No se pudo enviar el código. Inténtalo de nuevo.",
    "forgot.errorReset": "No se pudo cambiar la contraseña. Verifica el código.",
    "forgot.passwordTooShort": "La contraseña debe tener al menos 8 caracteres.",

    // Configuración inicial (primer arranque)
    "setup.title": "Crear Tu Primera Empresa",
    "setup.subtitle": "¡Bienvenido! Configura tu organización para comenzar a usar el sistema.",
    "setup.companyName": "Nombre de la Empresa",
    "setup.companyNamePlaceholder": "Acme Technologies S.A.",
    "setup.email": "Correo Electrónico",
    "setup.phone": "Teléfono",
    "setup.address": "Dirección",
    "setup.addressPlaceholder": "Calle Principal 123, Ciudad",
    "setup.ruc": "RUC / NIT",
    "setup.createCompany": "Crear Empresa",
    "setup.creating": "Creando...",
    "setup.doneTitle": "¡Empresa Creada!",
    "setup.doneDesc": "Tu empresa está lista:",
    "setup.goToDashboard": "Ir al Panel Principal",
    "setup.errorCreate": "No se pudo crear la empresa. Inténtalo de nuevo.",

    // Perfil
    "profile.loadError": "No se pudo cargar el perfil.",
    "profile.edit": "Editar Perfil",
    "profile.settings": "Configuración",
    "profile.personal": "Información Personal",
    "profile.contact": "Información de Contacto",
    "profile.professional": "Información Profesional",
    "profile.system": "Información del Sistema",
    "profile.companies": "Empresas Asignadas",
    "profile.firstName": "Nombre",
    "profile.lastName": "Apellido",
    "profile.userCode": "Código de Usuario",
    "profile.userId": "ID de Usuario",
    "profile.primaryEmail": "Email Principal",
    "profile.contactEmail": "Email de Contacto",
    "profile.phone": "Teléfono",
    "profile.username": "Nombre de Usuario",
    "profile.department": "Departamento",
    "profile.position": "Cargo",
    "profile.role": "Rol del Sistema",
    "profile.createdAt": "Creado",
    "profile.updatedAt": "Última Actualización",
    "profile.personId": "ID de Persona",
    "profile.accountActive": "Cuenta Activa",
    "profile.active": "Activo",
    "profile.inactive": "Inactivo",
    "profile.yes": "Sí",
    "profile.no": "No",

    // Navigation
    "nav.dashboard": "Panel Principal",
    "nav.devices": "Dispositivos",
    "nav.maintenance": "Mantenimiento",
    "nav.network": "Red",
    "nav.users": "Usuarios",
    "nav.persons": "Personas",
    "nav.tickets": "Tickets",
    "nav.expenses": "Gastos",
    "nav.licenses": "Licencias",
    "nav.documents": "Documentos",
    "nav.reports": "Reportes",
    "nav.inventory": "Inventario",
    "nav.settings": "Configuración",
    "nav.logout": "Cerrar Sesión",
    "nav.profile": "Perfil",
    "nav.noAccess": "No tienes acceso a ninguna ruta",
    "nav.openMenu": "Abrir menú principal",
    "nav.closeMenu": "Cerrar menú principal",
    "nav.closeSidebar": "Cerrar menú",

    // Common actions
    "action.create": "Crear",
    "action.edit": "Editar",
    "action.delete": "Eliminar",
    "action.save": "Guardar",
    "action.cancel": "Cancelar",
    "action.export": "Exportar",
    "action.import": "Importar",
    "action.search": "Buscar",
    "action.filter": "Filtrar",
    "action.view": "Ver",
    "action.download": "Descargar",
    "action.upload": "Subir",
    "action.report": "Reporte",
    "action.confirm": "Confirmar",
    "action.back": "Volver",
    "action.next": "Siguiente",
    "action.submit": "Enviar",
    "action.update": "Actualizar",
    "action.refresh": "Actualizar",
    "action.downloadTemplate": "Descargar Template",
    "action.importCSV": "Importar CSV",
    "action.importing": "Importando...",

    // Common labels
    "common.loading2": "Cargando...",
    "common.saving": "Guardando...",
    "common.deleting": "Eliminando...",
    "common.noData2": "No hay datos disponibles.",
    "common.actions": "Acciones",
    "common.status": "Estado",
    "common.date": "Fecha",
    "common.name": "Nombre",
    "common.description": "Descripción",
    "common.type": "Tipo",
    "common.category": "Categoría",
    "common.company": "Empresa",
    "common.notes": "Notas",
    "common.selected": "seleccionado(s)",
    "common.total": "Total",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.enabled": "Habilitado",
    "common.disabled": "Deshabilitado",
    "common.yes": "Sí",
    "common.no": "No",
    "common.all": "Todos",
    "common.none": "Ninguno",
    "common.required": "Requerido",
    "common.optional": "Opcional",
    "common.confirmDelete": "¿Estás seguro de que deseas eliminar este elemento?",
    "common.cannotUndo": "Esta acción no se puede deshacer.",
    "common.error": "Ocurrió un error",
    "common.success": "Operación exitosa",

    // Dashboard
    "dashboard.title": "Panel Principal",
    "dashboard.welcome": "Bienvenido",
    "dashboard.totalDevices": "Total Dispositivos",
    "dashboard.openTickets": "Tickets Abiertos",
    "dashboard.expiringLicenses": "Licencias por Vencer",
    "dashboard.pendingMaintenance": "Mantenimiento Pendiente",
    "dashboard.recentActivity": "Actividad Reciente",
    "dashboard.systemOverview": "Resumen del Sistema",
    "dashboard.quickStats": "Estadísticas Rápidas",

    // Devices
    "devices.title": "Dispositivos",
    "devices.all": "Todos los Dispositivos",
    "devices.create": "Nuevo Dispositivo",
    "devices.edit": "Editar Dispositivo",
    "devices.serialNumber": "Número de Serie",
    "devices.brand": "Marca",
    "devices.model": "Modelo",
    "devices.location": "Ubicación",
    "devices.assignedTo": "Asignado A",
    "devices.purchaseDate": "Fecha de Compra",
    "devices.warrantyExpiry": "Vencimiento Garantía",
    "devices.ipAddress": "Dirección IP",
    "devices.macAddress": "Dirección MAC",
    "devices.operatingSystem": "Sistema Operativo",
    "devices.processor": "Procesador",
    "devices.ram": "RAM",
    "devices.storage": "Almacenamiento",
    "devices.totalDevices": "Total Dispositivos",
    "devices.assigned": "Asignados",
    "devices.unassigned": "Sin Asignar",
    "devices.inWarranty": "En Garantía",
    "devices.deleteConfirm": "¿Eliminar dispositivo?",

    // Maintenance
    "maintenance.title": "Mantenimiento",
    "maintenance.all": "Todo el Mantenimiento",
    "maintenance.create": "Nuevo Mantenimiento",
    "maintenance.edit": "Editar Mantenimiento",
    "maintenance.type": "Tipo de Mantenimiento",
    "maintenance.scheduledDate": "Fecha Programada",
    "maintenance.completedDate": "Fecha de Completado",
    "maintenance.technician": "Técnico",
    "maintenance.cost": "Costo",
    "maintenance.priority": "Prioridad",
    "maintenance.pending": "Pendiente",
    "maintenance.inProgress": "En Progreso",
    "maintenance.completed": "Completado",
    "maintenance.cancelled": "Cancelado",
    "maintenance.preventive": "Preventivo",
    "maintenance.corrective": "Correctivo",
    "maintenance.totalMaintenance": "Total Mantenimientos",
    "maintenance.pendingCount": "Pendientes",
    "maintenance.completedCount": "Completados",
    "maintenance.deleteConfirm": "¿Eliminar registro de mantenimiento?",

    // Network
    "network.title": "Red",
    "network.all": "Toda la Red",
    "network.create": "Nuevo Dispositivo de Red",
    "network.edit": "Editar Dispositivo de Red",
    "network.ipAddress": "Dirección IP",
    "network.macAddress": "Dirección MAC",
    "network.subnet": "Subred",
    "network.gateway": "Puerta de Enlace",
    "network.dns": "DNS",
    "network.vlan": "VLAN",
    "network.port": "Puerto",
    "network.bandwidth": "Ancho de Banda",
    "network.totalDevices": "Total Dispositivos de Red",
    "network.online": "En Línea",
    "network.offline": "Desconectado",
    "network.deleteConfirm": "¿Eliminar dispositivo de red?",

    // Users
    "users.title": "Usuarios",
    "users.all": "Todos los Usuarios",
    "users.create": "Nuevo Usuario",
    "users.edit": "Editar Usuario",
    "users.email": "Correo Electrónico",
    "users.role": "Rol",
    "users.password": "Contraseña",
    "users.confirmPassword": "Confirmar Contraseña",
    "users.lastLogin": "Último Acceso",
    "users.totalUsers": "Total Usuarios",
    "users.admins": "Administradores",
    "users.deleteConfirm": "¿Eliminar usuario?",
    "users.superAdmin": "Super Admin",
    "users.admin": "Administrador",
    "users.moderator": "Moderador",
    "users.user": "Usuario",

    // Persons
    "persons.title": "Personas",
    "persons.all": "Todas las Personas",
    "persons.create": "Nueva Persona",
    "persons.edit": "Editar Persona",
    "persons.firstName": "Nombre",
    "persons.lastName": "Apellido",
    "persons.phone": "Teléfono",
    "persons.department": "Departamento",
    "persons.position": "Cargo",
    "persons.totalPersons": "Total Personas",
    "persons.withDevice": "Con Dispositivo",
    "persons.noDepartment": "Sin departamento",
    "persons.deleteConfirm": "¿Eliminar persona?",

    // Tickets
    "tickets.title": "Tickets",
    "tickets.all": "Todos los Tickets",
    "tickets.create": "Nuevo Ticket",
    "tickets.edit": "Editar Ticket",
    "tickets.subject": "Asunto",
    "tickets.requester": "Solicitante",
    "tickets.assignedTo": "Asignado A",
    "tickets.priority": "Prioridad",
    "tickets.status": "Estado",
    "tickets.open": "Abierto",
    "tickets.inProgress": "En Progreso",
    "tickets.resolved": "Resuelto",
    "tickets.closed": "Cerrado",
    "tickets.low": "Baja",
    "tickets.medium": "Media",
    "tickets.high": "Alta",
    "tickets.critical": "Crítico",
    "tickets.totalTickets": "Total Tickets",
    "tickets.openCount": "Abiertos",
    "tickets.resolvedCount": "Resueltos",
    "tickets.deleteConfirm": "¿Eliminar ticket?",

    // Expenses
    "expenses.title": "Gastos",
    "expenses.all": "Todos los Gastos",
    "expenses.create": "Nuevo Gasto",
    "expenses.edit": "Editar Gasto",
    "expenses.amount": "Monto",
    "expenses.vendor": "Proveedor",
    "expenses.invoiceNumber": "Número de Factura",
    "expenses.paymentDate": "Fecha de Pago",
    "expenses.software": "Software",
    "expenses.annual": "Anual",
    "expenses.totalExpenses": "Total Gastos",
    "expenses.annualTotal": "Total Anual",
    "expenses.deleteConfirm": "¿Eliminar gasto?",
    "expenses.application": "Aplicación",
    "expenses.costPerUser": "Costo",
    "expenses.downloadExcel": "Descargar Excel",
    "expenses.downloadPDF": "Descargar PDF",
    "expenses.unknownPerson": "Persona Desconocida",
    "expenses.tableHint": "La tabla muestra el costo por usuario para cada aplicación. Haz clic en el nombre de un Colaborador para ver el desglose de sus gastos. Los valores \"-\" indican que la persona no tiene asignada esa aplicación para los filtros actuales.",

    // Licenses
    "licenses.title": "Licencias de Software",
    "licenses.all": "Todas las Licencias",
    "licenses.create": "Nueva Licencia",
    "licenses.edit": "Editar Licencia",
    "licenses.softwareName": "Software",
    "licenses.licenseKey": "Clave de Licencia",
    "licenses.provider": "Proveedor",
    "licenses.activationDate": "Fecha de Activación",
    "licenses.expirationDate": "Fecha de Expiración",
    "licenses.noExpiration": "Sin expiración",
    "licenses.active": "Activa",
    "licenses.expiringSoon": "Por Vencer",
    "licenses.expired": "Expirada",
    "licenses.totalLicenses": "Total Licencias",
    "licenses.expiringSoonCount": "Por Vencer (30 días)",
    "licenses.expiredCount": "Expiradas",
    "licenses.deleteConfirm": "¿Eliminar licencia?",

    // Documents
    "documents.title": "Documentos",
    "documents.all": "Todos los Documentos",
    "documents.create": "Subir Documento",
    "documents.edit": "Editar Documento",
    "documents.fileUrl": "URL del Archivo",
    "documents.fileType": "Tipo de Archivo",
    "documents.equipment": "Equipo Asociado",
    "documents.noCategory": "Sin Categoría",
    "documents.totalDocuments": "Total Documentos",
    "documents.categories": "Categorías",
    "documents.withEquipment": "Con Equipo",
    "documents.deleteConfirm": "¿Eliminar documento?",

    // Reports
    "reports.title": "Reportes IT",
    "reports.all": "Todos los Reportes",
    "reports.generate": "Generar Reporte",
    "reports.dateRange": "Rango de Fechas",
    "reports.from": "Desde",
    "reports.to": "Hasta",

    // Inventory
    "inventory.title": "Inventario",
    "inventory.all": "Todo el Inventario",
    "inventory.create": "Nuevo Artículo",
    "inventory.edit": "Editar Artículo",
    "inventory.quantity": "Cantidad",
    "inventory.unitPrice": "Precio Unitario",
    "inventory.totalValue": "Valor Total",
    "inventory.deleteConfirm": "¿Eliminar artículo de inventario?",
    "inventory.inUse": "En Uso",
    "inventory.available": "Disponibles",
    "inventory.maintenance": "Mantenimiento",
    "inventory.damaged": "Dañados",
    "inventory.warranties": "Garantías",
    "inventory.cost": "Costo",
    "inventory.mostEquipment": "Más Equipos",
    "inventory.topDepts": "Top Deptos",
    "inventory.types": "Tipos",
    "inventory.allTypes": "Todos los Tipos",
    "inventory.allDepartments": "Todos los Departamentos",
    "inventory.noEquipment": "No hay equipos aún. Puedes agregar uno o importar un CSV.",
    "inventory.noCompany": "No se encontró el código de empresa.",
    "inventory.importComplete": "Importación Completada",
    "inventory.importWithErrors": "Importación con Errores",
    "inventory.totalRows": "Total Filas",
    "inventory.inserted": "Insertados",
    "inventory.skipped": "Omitidos",
    "inventory.errors": "Errores",
    "inventory.skippedRecords": "Registros Omitidos",
    "inventory.errorRecords": "Errores",
    "inventory.insertedRecords": "Registros Insertados",
    "inventory.row": "Fila",
    "inventory.importingMessage": "Por favor espera mientras procesamos tu archivo CSV...",
    "inventory.equipmentDeleted": "Equipo eliminado correctamente",
    "inventory.equipmentCreated": "Equipo creado correctamente",
    "inventory.noLocation": "Sin ubicación asignada",

    // Settings
    "settings.title": "Configuración",
    "settings.language": "Idioma",
    "settings.theme": "Tema",
    "settings.darkMode": "Oscuro",
    "settings.lightMode": "Claro",
    "settings.systemMode": "Sistema",
    "settings.profile": "Perfil",
    "settings.company": "Empresa",

    // Errors
    "error.notFound": "Página no encontrada",
    "error.unauthorized": "No autorizado",
    "error.serverError": "Error del servidor",
    "error.networkError": "Error de red",
    "error.loadData": "Error al cargar los datos",
    "error.saveData": "Error al guardar los datos",
    "error.deleteData": "Error al eliminar el elemento",
    "error.selectCompany": "Por favor selecciona una empresa primero",

    // Language
    "lang.en": "Inglés",
    "lang.es": "Español",
    "lang.switch": "Cambiar idioma",

    // Sidebar group labels
    "nav.group.general":        "General",
    "nav.group.infrastructure": "Infraestructura",
    "nav.group.resources":      "Recursos",
    "nav.group.finance":        "Finanzas",
    "nav.group.documentation":  "Documentación",
    "nav.group.support":        "Soporte",
    "nav.group.system":         "Sistema",

    // Settings nav tabs
    "settings.tab.general":     "General",
    "settings.tab.users":       "Usuarios",
    "settings.tab.companies":   "Compañías",
    "settings.tab.departments": "Departamentos",
    "settings.breadcrumb":      "Configuración",
    "settings.system":          "Sistema",
    "settings.appearance":      "Apariencia",

    // Red (adicional)
    "network.providers": "Proveedores",
    "network.decommissioned": "Desactivado",
    "network.unknown": "Desconocido",
    "network.allStatuses": "Todos los estados",
    "network.noNetworks": "No hay redes registradas",

    // Mantenimiento (adicional)
    "maintenance.thisMonth": "Este mes",
    "maintenance.requireAttention": "Requieren atención",
    "maintenance.totalCost": "Costo Total",

    // Compañías
    "companies.loadError": "Error al cargar compañías",
    "companies.registered": "registradas",
    "companies.new": "Nueva compañía",
    "companies.noCompanies": "No se encontraron compañías",
    "companies.users": "usuarios",
    "companies.equipments": "equipos",
    "companies.maintenances": "mant.",
    "companies.depts": "deptos",
    "companies.add": "Agregar",
    "companies.noDepartments": "Sin departamentos",
    "companies.deleteCompany": "Eliminar compañía",

    // Departamentos
    "departments.loadError": "Error al cargar departamentos",
    "departments.new": "Nuevo departamento",
    "departments.noDepartments": "No se encontraron departamentos",
    "departments.deleteDepartment": "Eliminar departamento",
  },
};

export default es;
